version: "3.8"

services:
  jwt-server:
    image: node:alpine
    restart: always
    command: 
      - npx
      - --package
      - jwt-novalnet-server
      - -y
      - start
    ports:
      - 9000:9000
